# Generated by Django 3.1.6 on 2021-02-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210213_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('NANNY', 'Nanny'), ('ONWER', 'Owner')], default='NONE', max_length=50, verbose_name='Type'),
        ),
    ]
