# Generated by Django 3.1.6 on 2021-02-14 07:25

import buupass.helpers.fancy_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210213_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default=buupass.helpers.fancy_generator.fancy_id_generator, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
