# Generated by Django 3.1.6 on 2021-02-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210213_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownermore',
            name='house_number',
        ),
    ]
