# Generated by Django 3.1.6 on 2021-02-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_ownermore_house_number'),
        ('authentication', '0003_auto_20210214_0725'),
    ]

    operations = [
    ]
