# Generated by Django 3.1.6 on 2021-02-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='date_completed',
            field=models.DateTimeField(blank=True),
        ),
    ]
