# Generated by Django 3.1.6 on 2021-02-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_auto_20210213_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='completed',
            field=models.BooleanField(blank=True),
        ),
    ]
