# Generated by Django 3.1.6 on 2021-02-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_auto_20210213_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chores',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
