# Generated by Django 3.1.6 on 2021-02-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_auto_20210213_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chores',
            old_name='updated_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='chores',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='chores',
            name='date_completed',
        ),
    ]
